import { Row, Col, Button } from 'react-bootstrap';
import CarouselWithModal from '../CarouselWithModal';
import snap1 from './screen1.png';
import snap2 from './screen2.png';
import snap3 from './screen3.png';
import snap4 from './screen4.png';
import snap5 from './screen5.png';

function SnapQuiz() {
  const snapImages = [snap1, snap2, snap3, snap4, snap5];

  return (
    <Row className="mb-5 align-items-center">
      {/* Screenshot Carousel */}
      <Col md={5} className="text-center mb-3 mb-md-0">
        <CarouselWithModal images={snapImages} />
      </Col>

      {/* Project Info */}
      <Col md={7}>
        <h3 className="text-decoration-underline">SnapQuiz</h3>
        <p>
          <strong>SnapQuiz</strong> is an interactive memory-based game that challenges users to memorize random images 
          and then answer multiple-choice questions generated by <strong>Google Gemini AI Vision</strong>. 
          Built with a full-stack architecture, it combines web scraping, AI integration, and dynamic quiz logic 
          into a fun, fast-paced experience.
        </p>

        <p><strong>Tech Stack:</strong> React, Bootstrap 5, React Router, Axios, Flask, Google Gemini AI, BeautifulSoup, Pillow, Git & GitHub, Heroku.</p>

        <p>
          <strong>My Contributions:</strong>
          <ul>
            <li>Integrated Google Gemini AI Vision API to analyze images and dynamically generate quizzes.</li>
            <li>Implemented Flask backend to fetch, scrape, process, and send image data to the AI model.</li>
            <li>Built modular React frontend with multiple game modes and responsive UI/UX design.</li>
            <li>Handled web scraping with BeautifulSoup and image conversion with Pillow.</li>
            <li>Designed full game loop: image display, memory timer, quiz interaction, and score reveal.</li>
          </ul>
        </p>

        <Button
          variant="primary"
          href="https://snapquiz-frontend-489546fcd686.herokuapp.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Live Demo
        </Button>
      </Col>
    </Row>
  );
}

export default SnapQuiz;
